# -*- coding: utf-8 -*-
"""matplotlib_polar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOTTB3-HxeKW1-ztlIqhD1_hMIBpHWr4
"""

import matplotlib.pyplot as plt
import numpy as np
    
qualities = ["Ad-hocracy", "Market", "Hierarchy",
            "Clan"]
  
now = [10, 15, 30, 45]
preferred = [15, 45, 30, 10]

# have to add the first element to the end of the list for the 
# shape to close in on itself.
now.append(now[0])  
preferred.append(preferred[0])


# Initialing the spiderplot by 
# setting figure size and polar
# projection
plt.figure(figsize =(10, 10))
ax = plt.subplot(polar = True)
    
# splitting the circle into appropriate quadrants on the length of attributes.
theta = np.linspace(0, 2 * np.pi, len(now))  
    
# Arranging the grid into number of attributes into equal parts in degrees
lines, labels = plt.thetagrids(range(0, 360, int(360/len(qualities))),
                                                         (qualities))
# Plot current attributes
ax.plot(theta, now, color='r', linestyle=':')
    
# Plot preferred attributes
ax.plot(theta, preferred, color='tab:red', linestyle='-')
    
# Add legend and title for the plot
ax.legend(labels =('Current', 'Preferred'),
           loc = 2)
plt.title("Current vs. Preferred Organizational Characteristics")

ax.set_theta_offset(pi/4)  # slanting grid 45 degrees
ax.grid(True) 

# Dsiplay the plot on the screen
plt.show()